### ISSUE TITLE
Determine what NEAD data we want prior to the meeting

### ISSUE THREAD

**Issue by kcranston** [arlin/hip_hack_howto#1]
If there is data from NEAD that we that isn't available from the lists of [science products](http://nescent.org/science/products.php) and [informatics products](http://nescent.org/informatics/products.php) on the nescent site, it would be good to know about that in advance of the meeting.

**Comment by aidanbudd** [comment]
Karen wrote this before the meeting:

If there is data from NEAD that we that isn't available from the lists of science products and informatics products on the nescent site, it would be good to know about that in advance of the meeting.

As we're now post-meeting, I'll close this, the issues have spread into a range of different issues now.

**Comment by aidanbudd** [comment]
Trying to close the issue - first time I've ever tried that on github, might take a few tries :)
