### ISSUE TITLE
Flights canceled - but rebooked no problem

### ISSUE THREAD

**Issue by aidanbudd** [arlin/hip_hack_howto#10]
Hi all;

yeah, flight was cancelled, but on the plus size I just got back from an appropriate last US meal of Waffle House breakfast at around midnight. Just like in the movies ;)

Maybe see you at the airport tomorrow, Shann!

Aidan

**Comment by kcranston** [comment]
Nicely done. Hope the rest of the travels are uneventful!

**Comment by rvosa** [comment]
"on the plus size" <- I see what you did there :)

**Comment by aidanbudd** [comment]
And thanks, Rutger, for giving me the chink of an opportunity to mention 
that it took 48 hours to get home in the end, but not so bad, gave me a 
chance to buy extra clothes to deal with limited laudry opporutnities, 
add to my collection of europe-to-uk plug adaptors, eat hotdogs in 
chicago etc. :)

On 18/03/2015 11:16, Rutger Vos wrote:

> "on the plus size" <- I see what you did there :)
> 
> On Mon, Mar 16, 2015 at 4:11 AM, aidanbudd notifications@github.com wrote:
> 
> > Hi all;
> > 
> > yeah, flight was cancelled, but on the plus size I just got back from an
> > appropriate last US meal of Waffle House breakfast at around
> > midnight. Just
> > like in the movies ;)
> > 
> > Maybe see you at the airport tomorrow, Shann!
> > 
> > Aidan
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/arlin/hip_hack_howto/issues/10.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arlin/hip_hack_howto/issues/10#issuecomment-82908118.

## 

Aidan Budd
Senior Project Manager for Bioinformatics
EMBL Heidelberg
About.me: http://about.me/aidan.budd
LinkedIn: https://de.linkedin.com/in/aidanbudd
Twitter:  @AidanBudd

**Comment by hlapp** [comment]
Wow - sorry Aidan it turned into such a nightmare! Clearly some higher
power felt that what you really wanted is getting more of the American
culture experience as epitomized by its airports ;-)

**Comment by aidanbudd** [comment]
:) aye, to be positive, I got to try lots more (good) hotdogs than I 
would have otherwise!

On 18/03/2015 12:44, Hilmar Lapp wrote:

> Wow - sorry Aidan it turned into such a nightmare! Clearly some higher
> power felt that what you really wanted is getting more of the American
> culture experience as epitomized by its airports ;-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arlin/hip_hack_howto/issues/10#issuecomment-82953601.

## 

Aidan Budd
Senior Project Manager for Bioinformatics
EMBL Heidelberg
About.me: http://about.me/aidan.budd
LinkedIn: https://de.linkedin.com/in/aidanbudd
Twitter:  @AidanBudd

**Comment by rvosa** [comment]
...on the plus size ;-)
