### ISSUE TITLE
requesting NESCent support for research or products

### ISSUE THREAD

**Issue by arlin** [arlin/hip_hack_howto#12]
NESCent supports its working groups by entertaining requests for additional funds to support specific projects.  Hilmar indicates there is a potential for a student to work on a project.  A student could be used for data entry, for instance.  

The data group will consider (at its next telecon) asking for a student to complete some of its work.  Perhaps we should bring Jonathon in on that.  

However, I would like to mention that there are other things that we could propose, like producing instructional materials such as screencasts.

**Comment by aidanbudd** [comment]
There are still quite a few github and twitter handles to be filled in, and it's (I expect) for someone who didn't participate in the hackathons, work for another 6 hours, could be more, to do the googling etc. needed to fill these out.

If I can do this, then so can someone else who didn't participate in the hackathons, I suggest we request NESCent funds to pay for a student to do this for us.

As suggested above, I recommend we aim to improve the quality/accuracy of this data by having the input data reviewed by one of the LT, and additionally by emailing all participants to request they confirm/correct the data, or provide data we couldn't find.

**Comment by arlin** [comment]
no really you should let me do that.  it will take me much less time.  your time is more valuable than that.

On Mar 16, 2015, at 5:10 PM, aidanbudd <notifications@github.com<mailto:notifications@github.com>> wrote:

There are still quite a few github and twitter handles to be filled in, and it's (I expect) for someone who didn't participate in the hackathons, work for another 6 hours, could be more, to do the googling etc. needed to fill these out.

If I can do this, then so can someone else who didn't participate in the hackathons, I suggest we request NESCent funds to pay for a student to do this for us.

As suggested above, I recommend we aim to improve the quality/accuracy of this data by having the input data reviewed by one of the LT, and additionally by emailing all participants to request they confirm/correct the data, or provide data we couldn't find.

—
Reply to this email directly or view it on GitHubhttps://github.com/arlin/hip_hack_howto/issues/12#issuecomment-81941494.

---

Arlin Stoltzfus (arlin@umd.edumailto:arlin@umd.edu)
Research Biologist, NIST; Fellow, IBBR; Adj. Assoc. Prof., UMCP
IBBR, 9600 Gudelsky Drive, Rockville, MD, 20850
tel: 240 314 6208; web: www.molevol.orghttp://www.molevol.org

**Comment by arlin** [comment]
The data group discussed this today and we decided against this, due to a combination of factors, namely that time is running out (for NESCent), we'd like to focus on the manuscript, and we don't really have a project ready to go for this.
