### ISSUE TITLE
Adding ideas for specific data-focused figures/tables

### ISSUE THREAD

**Issue by aidanbudd** [arlin/hip_hack_howto#13]
I've started a section at the end of the manuscript with a list of possible data-driven figures/tables we could include. Perhaps this is better stored in a separate file, or in the data repo? I'll just leave it in the manuscript unless others think it would be much better elsewhere.

**Comment by rvosa** [comment]
I am still fantasizing about some sort of social graph, e.g. with nodes being people and edges being any harvestable link between them (github/twitter following) and when this link was created (pre- or post- hackathon). Wouldn't that be fun?

**Comment by arlin** [comment]
The fantasy graph that I want to see aims even higher to establish a community-wide impact on _interoperability_ specifically.  The aim of HIP and EvoIO was to grow a network of interoperable resources.  Some links between data resources were established by our hackathons, or using our  interoperability stack (NeXML, CDAO, PhyloWS).  I'm going to check in a sketch of this graph from a few years ago.  It's in dot format.

**Comment by arlin** [comment]
I added this material under "emerging_network".  Right now I'm not sure that it can be leveraged in any way for this project.  But maybe it could.  Have a look at the dot file and see what you think.

**Comment by aidanbudd** [comment]
Currently failing to get Graphviz working on my Mavericks machine - maybe you could add a jpg?

**Comment by epontell** [comment]
Need to remove the last comment line from the file to be able to view it (lines 67-68)

**Comment by epontell** [comment]
Created a PDF version for you

**Comment by arlin** [comment]
Aidan, my bad.  GraphViz wasn't working on the dot file because it was missing a closing brace.  I'll fix it now.

**Comment by rvosa** [comment]
Seeing that we don't have the data to put our fantasy graphs together I don't see this issue going anyway (it's now a year and a half ago...) so I'm closing this.
