### ISSUE TITLE
Feedback questionaires?

### ISSUE THREAD

**Issue by aidanbudd** [arlin/hip_hack_howto#14]
Were feedback forms/questionaires collected from all (any?) of the hackathons? If so, and if all the forms had some similar/same questions in them, we could use that info to describe the impact as rated by participants?

**Comment by rvosa** [comment]
I may be wrong here but I don't think we collected feedback questionnaires ever - other than for updating NEAD, that is.

**Comment by aidanbudd** [comment]
I'm going to close this issue, and move it over to the data repo, integrating it with discussion of this, and other things, we could consider going back to hackathon participants now and asking them for
