### ISSUE TITLE
reorganization suggestion: feedback request

### ISSUE THREAD

**Issue by arlin** [arlin/hip_hack_howto#15]
I'd like to re-organize some of the material in the manuscript.  I'd like to start later today if I have time.  Please give me your comments.  What we have now (IMHO) naturally falls into the following categories of content: 
1. description of NESCent model, including details of our chosen practices, why we chose them, and anecdoes to illustrate them (e.g., we scoped hackathon 2 in such and such a way), _but not opinions, hypotheses, or attempts to draw lessons from evidence_.  
2. description of impacts
   - tangible impacts we can document clearly, such as code repos, pubs, posters, etc
   - less tangible impacts, harder to document but just as important
3. "lessons learned" where we have experience-based advice to offer
4.  open issues and further work, including hypothesis (e.g., Mike's idea), ways to document hackathons more effectively, other research questions, etc.

The problem right now is that these are somewhat mixed together.  There is some "lessons learned" stuff in the model description, and this is followed by quite a lot about intangible impacts.  The rest of the stuff is mixed together in Results-Discussion.  I would suggest that we streamline 1, and then apply the categories 2, 3 and 4 above as separate sections.  

Whether we want to use "intro-results-discussion" is a separate issue. I'm talking about the second-level organization of the material, not the top level. We can stay flexible on that.  

Shall I go ahead and re-organize along those lines?

**Comment by aidanbudd** [comment]
Mike, as manuscript 'lead' what would you prefer we do here? I already 
did a bit of reorganising myself.

I'd recommend Arlin does make changes of this kind, I think him coming 
at this anew makes him likely to see patterns etc. that aren't so 
obvious when one is hacking away creating the initial content.

If we decide to change the order again later, it's probably not so much 
work.

My 2 cents.

On 19/03/2015 15:09, Arlin Stoltzfus wrote:

> I'd like to re-organize some of the material. What we have now (IMHO)
> naturally falls into the following categories:
> 1. description of NESCent model, including details of our chosen
>    practices, why we chose them, and anecdoes to illustrate them (e.g.,
>    we scoped hackathon 2 in such and such a way).
> 2. description of tangible impacts we can document clearly, such as
>    code repos, pubs, posters, etc
> 3. descriptions of less tangible impacts, harder to document
> 4. "lessons learned" where we have high-level advice to offer,
>    typically based on anecdotes
> 5. open issues and further work, including hypothesis to be tested
>    (e.g., Mike's idea), ways to document hackathons more effectively,
>    other research questions, etc.
> 
> The problem right now is that these are somewhat mixed together. There
> is some "lessons learned" stuff in the model description, and q
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arlin/hip_hack_howto/issues/15.

## 

Aidan Budd
Senior Project Manager for Bioinformatics
EMBL Heidelberg
About.me: http://about.me/aidan.budd
LinkedIn: https://de.linkedin.com/in/aidanbudd
Twitter:  @AidanBudd

**Comment by msrosenberg** [comment]
A number of these issues are things we recognized as we were writing; some were fixed and others were left for later, in part because it was better to flesh out sections than to nitpick structure during the limited time period at NESCent. It was not at all obvious (to me) where to place the discussion of impacts and values; I personally leaned toward having it in the discussion, rather than the intro where we currently have it, but when we wanted to justify certain process decisions, having it toward the beginning made sense.

I'm fine with Arlin re-organizing in this model if he think she can restructure it to meet this logic flow.

**Comment by arlin** [comment]
OK, I did the reorganization and updated the TOC.  The _content_ is still pretty much what it was, although I deleted 10 or 20 lines of text that seemed to be unnecessary. 

This gives me (at least) a much clearer picture of how to move forward with further revisions.
