### ISSUE TITLE
add pop gen hackathon

### ISSUE THREAD

**Issue by arlin** [arlin/hip_hack_howto#17]
Right now the manuscript is written to refer to a set of 8 hackathons from 2006 to 2014.  But the data set includes hackathon 9, the March 2015 one.  This needs to be fixed several places in the manuscript if we are going to include hackthon 9.

**Comment by msrosenberg** [comment]
Have we made a decision about this? For now I'll flag places where this might need to be changed if we add the last one.

**Comment by arlin** [comment]
I added a row to Table 1 for the r  hackathon.

**Comment by arlin** [comment]
I added a row to Table 1 for this.

**Comment by arlin** [comment]
I looked at the information we have on this event in the hackathon_data repo.  We basically have everything except the top-level md file describing the event.

**Comment by arlin** [comment]
I have updated the manuscript to refer to 9 hackathons instead of 8, 54 projects instead of 49, and so on.   There are 2 more things to be done.   First, we need to reference aspects of the popgenr hackathon like we do for the other hackathons.  Second, we need to update the diversity figures.  I'll close this issue and make that a separate issue.

**Comment by arlin** [comment]
Actually, the diversity figures that Enrico made already have the data from event 9.  So we are good.
