### ISSUE TITLE
add graphic illustrating typical day 1 schedule

### ISSUE THREAD

**Issue by arlin** [arlin/hip_hack_howto#18]

**Comment by rvosa** [comment]
Do we feel like we have a canonical description of the day 1 schedule or is this the moment to flesh that out? The manuscript outlines:
- Welcome and introductions ("brief")
- Technical presentations ("90min - several hours")
- Open discussion ("The appropriate time to end the discussion is when participants are ready to proceed to the next stage")
- Initial pitches and feedback (how long? number of pitches \* X minutes)
- Team formation and pitch refinement (how long?)
- Solidification of team plans (optional)

**Comment by epontell** [comment]
Sounds right to me. Looking at the schedule of the events, some cases saw technical presentations being made after pitches (I guess to facilitate selecting topics relevant to the projects).

Enrico

---

College of Arts & Sciences
New Mexico State University
Las Cruces, NM 88003

**Comment by arlin** [comment]
Here are some graphical ideas ![image](https://cloud.githubusercontent.com/assets/1659198/6923769/d0a2ccb0-d7a1-11e4-8a83-a6daf9bb9bf1.png)

**Comment by arlin** [comment]
ok, getting this to work in github now.  Here are some graphical ideas for anyone who wants to try this (don't assume that the times are right).  We could do a timeline with braces, or with trapezoidal blocks.  

![graphic](https://cloud.githubusercontent.com/assets/1659198/6923845/4e04785c-d7a2-11e4-92eb-3504a25b00fe.jpg)

**Comment by arlin** [comment]
I think the last action for the day is "teams report out", i.e., teams stand up and present their revised plan and their roster.  

As I recall, we sometimes had multiple bouts of discussion, ideas and technical talks.  

With respect to the exact timeline, here are my suggestions: 
- Welcome and introductions - 30 to 45 min
- Technical presentations - 60 to 150 min
- Open discussion - total 60 to 150 min, may alternative with structured discussion & pitch ideas
- [lunch break]
- Initial pitches and feedback - limit to 45 to 60 min no matter how many pitches
- Team formation and pitch refinement - 60 to 90 minutes 
- Teams report back to group - 20 to 30 min

**Comment by hlapp** [comment]
> Technical presentations - 60 to 150 min

I would normally refer to this block of time as "stage-setting talks". Usually these would be presented by users (helping to drive home pain points), and/or some big picture talk that brings everyone on the same page with regard to context and scope.

Is this what you mean by "Technical Presentations"? When I see "Technical presentations" I think bootcamps, but presumably you mean something else?

**Comment by rvosa** [comment]
Are we still doing this? In the manuscript we're not referencing a figure like this. Maybe this is not necessary?

**Comment by hlapp** [comment]
I think it would be very useful to have from a reader's perspective.

**Comment by rvosa** [comment]
Ok, I can work on this.

**Comment by rvosa** [comment]
I've added a figure (named fig4.pdf) to the stash on overleaf.

**Comment by hlapp** [comment]
I assume the figure caption will explain what the tick marks stand for?

![fig4.pdf](https://github.com/NESCent/hip_hack_howto/files/639798/fig4.pdf)

**Comment by rvosa** [comment]
Time. Minor tick marks 15 minutes, then 30, then 60.
Op Thu, 8 Dec 2016 om 16:16 schreef Hilmar Lapp <notifications@github.com>
