### ISSUE TITLE
Move manuscript to proper document editor

### ISSUE THREAD

**Issue by msrosenberg** [arlin/hip_hack_howto#19]
So I've quickly read through the entire manuscript and made a few minor edits (and added a temp figure to the intro), but before I go back and tackle it more fully, I feel that it's time to abandon the wiki model and move to a lead-author model. 

Our two primary options are Word and Google Docs. I just discovered that, as of December, Google Docs has a track changes-like option. It's called "Suggestions" and you can turn it on via the Editing menu (http://www.pcmag.com/article2/0,2817,2473185,00.asp). 

My "suggestion" is that we transfer the manuscript to Google Docs, allowing us to have synchronous editing when necessary, but also have change tracking on (as long as everyone enables it). If everyone agrees, I'm happy to do the grunt work of the transfer. I'll set up the Doc, do a more major editing pass, then invite everyone (you may need to send me the email address you prefer to use for Google Docs).

**Comment by epontell** [comment]
Googledocs is good with me. 

Enrico

---

College of Arts & Sciences
New Mexico State University
Las Cruces, NM 88003

**Comment by rvosa** [comment]
Fine with me.

**Comment by arlin** [comment]
I'm OK with google docs.   Eventually we'll have to go to Word + DropBox, right?   But I think that should be put off to as late as possible to avoid clashes.

**Comment by shannoliver** [comment]
Google Docs works great.

**Comment by msrosenberg** [comment]
I'm in the process of doing this now. Will close when I'm ready to invite everyone else.

**Comment by hlapp** [comment]
:+1:

**Comment by msrosenberg** [comment]
This part is done and everyone has hopefully been invited. Contact me directly if you don't have access to the ms.
