### ISSUE TITLE
Create a shared mendeley library for relevant literature

### ISSUE THREAD

**Issue by rvosa** [arlin/hip_hack_howto#2]
Right?

**Comment by aidanbudd** [comment]
Never used Mendeley before, if I've time I'll try this out, and/but if that's really quick/easy for you Rutger and you have the time, great if you set it up.

**Comment by epontell** [comment]
Is it still free of charge to create a Mendely community?

Enrico

From:  aidanbudd
Reply-To:  arlin/hip_hack_howto
Date:  Thursday, February 26, 2015 at 2:21 AM
To:  arlin/hip_hack_howto
Subject:  Re: [hip_hack_howto] Create a shared mendeley library for 
relevant literature (#2)

Never used Mendeley before, if I've time I'll try this out, and/but if 
that's really quick/easy for you Rutger and you have the time, great if 
you set it up.

**Comment by rvosa** [comment]
It is free of charge if it is an "open" group - which, for our purposes, should be fine. I created a group and invited Hilmar, Arlin and Karen, because they are the only participants to whom I am currently connected on Mendeley. Here is the group: http://www.mendeley.com/groups/6731181/hip-hack-howto/

**Comment by hlapp** [comment]
I was wondering whether we can't just do with a bibtex file in this repo.

**Comment by rvosa** [comment]
In 99 out of 100 cases I am also a big fan of plain text data but I really
don't think this is practical for this case. While we're assembling the
bibliography, wouldn't it be nice to just use the bookmarklet? And when
we're cleaning things up, e.g. alternate author names, wouldn't it be nice
to use the facilities in mendeley desktop for that? Also, the word plugin
for mendeley has actually become usable. For the time being my vote is to
use mendeley, but I am easily swayed by good arguments.

**Comment by hlapp** [comment]
I have no objections to Mendeley, I just don't use it anymore. However, it's easy enough to pull down stuff from there as Bibtex, so this question doesn't need to be about one or the other.

**Comment by rvosa** [comment]
Cool. If we're interested in pursuing the literature analysis idea than
exporting to bibtex is likely a good idea anyway.

**Comment by rvosa** [comment]
I have added all the locatable references that are cited at the bottom of manuscript.md to the Mendeley library. At this point I suppose we could export this to BibTex or continue on with Mendeley, whatever the preference may be.

**Comment by arlin** [comment]
Thanks Rutger!  I'm going to close this.  Choosing the next step is a separate issue.
