### ISSUE TITLE
describe changes in how we implemented hackathon model

### ISSUE THREAD

**Issue by arlin** [arlin/hip_hack_howto#20]
I'm doing a brain-dump here of some stuff that might go in the manuscript.  

I was digging up information on scoping statements and requests-for-participation today.  I was struck by the fact that, for event 1, there was no open call, and we actually had a pre-determined list of projects (worked out with participants in pre-event telecons).  In events 2 and 3, some seats were filled by nomination and some by open call.  We asked nominees to fill out the application form, but we didn't score their applications.  There was resistance to the idea of scoring people we had hand-picked and asked to apply.  I'm not exactly sure of the protocol for events 4 and 5 (VoCamp and GMOD).  

By the time we got to event 6, everyone had to apply and was reviewed, although we encouraged certain key project personnel to apply.  Our attitude, ultimately, is that everyone applies in the same way and is subject to the same review, and the only difference is that, for strategic reasons, some people are being encouraged actively to apply.  

I think that our ability to rely almost completely on an open call in 2012 was based partly on the increasing popularity of hackathons, and partly on how we cultivated a reputation & community connections.  I don't think it could have worked in 2006.

**Comment by arlin** [comment]
The process for hackathon #1 is described in the publication by Lapp, et al 2007.

**Comment by rvosa** [comment]
The group formation was also different in hackathon 1: participants coalesced around the projects they were already involved in (e.g. Mesquite, Bio* toolkits, HyPhy) so there was less of a spirit of teaming up with people you normally wouldn't. This is now noted in the manuscript.
