### ISSUE TITLE
Identify the venue for the manuscript

### ISSUE THREAD

**Issue by msrosenberg** [arlin/hip_hack_howto#21]
We discussed this a little at the end of the first meeting, but never settled on anything. Some suggestions (from then as well as additional ones) are:
- Journal of Open Research Software (http://openresearchsoftware.metajnl.com)
  - Hilmar believed they'd agree to accept something like this quickly. My own take is this isn't appropriate for them (and they have major length constraints)
- PLOS Biology 
- PLOS Comptutational Biology 
  - I think PLOS CB would be more appropriate than PLOS Biology
- PLOS ONE
  - Length isn't an issue, but not sure if it meets their primary research agenda
- BMC Bioinformatics
  - Not sure it quite fits, but we could send a letter of inquiry

**Comment by msrosenberg** [comment]
While there are still some sections whose writing is incomplete (while much more that still needs editing), we probably shouldn't do too much more writing before identifying the venue.

**Comment by hlapp** [comment]
> Journal of Open Research Software (http://openresearchsoftware.metajnl.com)
> - Hilmar believed they'd agree to accept something like this quickly. My own take is this isn't appropriate for them (and they have major length constraints)

Indeed, I didn't see this. Perhaps we can submit a pre-submission inquiry to the EIC (@npch) about waiving the length restriction? (Neil, you can get an overview of the manuscript from the [abstract](https://github.com/arlin/hip_hack_howto/blob/master/manuscript.md#abstract). And apparently Matt Turk isn't on Github, so can't tag him - could you forward to him?). 

If JORS isn't willing to waive the length restriction, I agree they don't seem like a good option. (And perhaps @npch or Matt Turk won't find the manuscript appropriate for JORS to start with.)

**Comment by npch** [comment]
Matt was on GitHub as @MatthewTurk but I'll forward separately.

We can waive the length restriction, though we would probably still look
for the paper to come in at around 12 pages excluding references.

In terms of scope Matt will have his own opinions, but my view is that it's
an interesting experience report which would be in scope if the authors
explicitly discuss whether there are any aspects which suit
research/scientific software hackathons (which might include - is the
spread of roles different from the other sort of hackathons which have been
studied in non science areas; are the defining factors on the optimal
length of a hackathon influenced by the participants?)

I'd be happy for you to self-publish a long version as a technical report,
and submit a summary version with added discussion on the impact of
hackathons on research software development to JORS in the Issues in
Research Software track.

As suggestions for other avenues, CSCW would be one appropriate conference
if you were seeking to present this as a research study, though clearly
this is not quick turnaround. CiSE might be another avenue, though they are
not OA yet (but do allow author re-publishing of articles).

On 6 April 2015 at 14:39, Hilmar Lapp notifications@github.com wrote:

> Journal of Open Research Software (http://openresearchsoftware.metajnl.com
> )
> - Hilmar believed they'd agree to accept something like this quickly. My
>   own take is this isn't appropriate for them (and they have major length
>   constraints)
> 
> Indeed, I didn't see this. Perhaps we can submit a pre-submission inquiry
> to the EIC (@npch https://github.com/npch) about waiving the length
> restriction? (Neil, you can get an overview of the manuscript from the
> abstract
> https://github.com/arlin/hip_hack_howto/blob/master/manuscript.md#abstract.
> And apparently Matt Turk isn't on Github, so can't tag him - could you
> forward to him?).
> 
> If JORS isn't willing to waive the length restriction, I agree they don't
> seem like a good option. (And perhaps @npch https://github.com/npch or
> Matt Turk won't find the manuscript appropriate for JORS to start with.)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arlin/hip_hack_howto/issues/21#issuecomment-90069021.

## 

Neil Chue Hong
Director, Software Sustainability Institute
EPCC, University of Edinburgh, JCMB, Edinburgh, EH9 3FD, UK
Tel: +44 (0)131 650 5957
http://www.software.ac.uk/

LinkedIn: http://uk.linkedin.com/in/neilchuehong
Twitter: http://twitter.com/npch
ORCID: http://orcid.org/0000-0002-8876-7606

**Comment by aidanbudd** [comment]
I looked at doing a presubmission Inquiry at PLoS Comp Bio for this, but didn't see any way of specifying  it should be considered for the education section; I'll mail Francis Ouellette to check with him whether it's best to submit it (the presub inquiry) via their official system, or to just mail him (as one of the two editors of the section) about it. If I don't hear back from him, I'll submit via their official system early next week.

**Comment by matthewturk** [comment]
I feel similarly to @npch -- emphasizing the way that the hackathons interact with research software concerns could bring it into scope for JORS in the Issues in Research Software submission track.  I'm personally quite interested in this paper, but I think Neil's suggestion about the longer technical paper and a shorter one focused on RS dev would be a good route.

**Comment by aidanbudd** [comment]
Francis replied already, said that (in response to the short info I gave him, see below) 

"In any case, the submission will get considered by staff and myself, and at this stage it is looking good. Recall the prefered word length (2,500+ 1 or 2 image or table), and that it will be peer-reviewed. I guess it’s not quite a tutorial (or maybe you will write it like that?), or a perspective? That aspect is always difficult to pinpoint, and any suggestion will be welcome."

Given this, I'll write a more detailed inquiry for them now; I'll share it with you by mail to check we're coming from the same place, and aim to send it early next week.

---

(slightly edited version of) what I mailed Francis:

We're writing a paper on lessons learnt from 9 hackathons run at NESCent focused on bioinformatics tools for interoperability of phylogenetic data.

These hackathons had both 'typical' goals of developing tools, but also very deliberate goals of educating and training participants in best-practices for software development, giving them training and experience using common tools (e.g. git/github), and for community-building.

The manuscript will present data for assessing how well the hackathons achieved these goals, along with lessons learnt from our experience organising these events. The main target group of the paper is people wanting to run their own hackathons, giving them guidelines on how to do this in a way most likely to achieve their goals, and on how to make it easier to demonstrate (for themselves, sponsors, and others) that they achieved these.

We thought this might fit the PLoS Comp Bio education section, despite not being a typical "quick guide" or tutorial. Rather, we thought that the lessons learned, and the focus on demonstrating positive impact in terms of adoption by participants of new tools and community building, might fit within 'resources for training scientists at all stages of their careers.'

We already have a lot of text, and have collected and done some analysis of data; before polishing it we wanted to decide where to try and publish it, to help us fit it as well as possible for that venue.

**Comment by epontell** [comment]
Looks promising

From:  aidanbudd notifications@github.com
Reply-To:  arlin/hip_hack_howto
<reply+0014c3285b8393f29ca1c65952e9d79ca6e12a371772be4a92cf00000001114629bb9
2a169ce03f71a39@reply.github.com>
Date:  Wednesday, April 15, 2015 at 7:29 AM
To:  arlin/hip_hack_howto hip_hack_howto@noreply.github.com
Subject:  Re: [hip_hack_howto] Identify the venue for the manuscript (#21)

Francis replied already, said that (in response to the short info I gave
him, see below) 

"In any case, the submission will get considered by staff and myself, and at
this stage it is looking good. Recall the prefered word length (2,500+ 1 or
2 image or table), and that it will be peer-reviewed. I guess it¹s not quite
a tutorial (or maybe you will write it like that?), or a perspective? That
aspect is always difficult to pinpoint, and any suggestion will be welcome."

Given this, I'll write a more detailed inquiry for them now; I'll share it
with you by mail to check we're coming from the same place, and aim to send
it early next week.

(slightly edited version of) what I mailed Francis:

We're writing a paper on lessons learnt from 9 hackathons run at NESCent
focused on bioinformatics tools for interoperability of phylogenetic data.

These hackathons had both 'typical' goals of developing tools, but also very
deliberate goals of educating and training participants in best-practices
for software development, giving them training and experience using common
tools (e.g. git/github), and for community-building.

The manuscript will present data for assessing how well the hackathons
achieved these goals, along with lessons learnt from our experience
organising these events. The main target group of the paper is people
wanting to run their own hackathons, giving them guidelines on how to do
this in a way most likely to achieve their goals, and on how to make it
easier to demonstrate (for themselves, sponsors, and others) that they
achieved these.

We thought this might fit the PLoS Comp Bio education section, despite not
being a typical "quick guide" or tutorial. Rather, we thought that the
lessons learned, and the focus on demonstrating positive impact in terms of
adoption by participants of new tools and community building, might fit
within 'resources for training scientists at all stages of their careers.'

We already have a lot of text, and have collected and done some analysis of
data; before polishing it we wanted to decide where to try and publish it,
to help us fit it as well as possible for that venue.


Reply to this email directly or view it on GitHub
https://github.com/arlin/hip_hack_howto/issues/21#issuecomment-93398606 .

**Comment by arlin** [comment]
Mike suggested originally that we should decide on venue before proceeding further with revisions.  That certainly makes sense if we are considering options such as self-publishing a long version and then writing a precis for JORS.  That sounds like extra work to me.  But anyone who is actually interested in the short version will become aware of the long version.  If we can get the short version into a venue that gives us very good exposure, then perhaps it is worth the effort.  

Could other people weigh in on this issue so that we can reach some kind of decision?   Or do we need to have a live meeting for that?

**Comment by aidanbudd** [comment]
At the moment, I'm assuming we'll make the presubmission inquiry to PLOS Comp Bio (see my mail about that), and once we hear back from them, we can make the decision about the venue (maybe at a live meeting, maybe by via consensus email discussion)

**Comment by aidanbudd** [comment]
I've just mailed the presubmission inquiry to PLOS Comp Bio; they indicate they try to deal with these within a week.

**Comment by rvosa** [comment]
Great, thanks!

**Comment by arlin** [comment]
Thanks for all your work on this, Aidan.  At the meeting today, we made a decision based on your report.  The vote was unanimous that F1000 is our first choice, and nearly unanimous that PeerJ (not compsci) is our second choice.
