### ISSUE TITLE
Community editing of manuscript

### ISSUE THREAD

**Issue by msrosenberg** [arlin/hip_hack_howto#22]
The refactoring of the manuscript is now complete. I'll be sending an invite to join the Google Doc momentarily. If you do not get an invite, please contact me with the email address you want to use. Also, when making any edits, please remember to turn "suggesting" on (under the Editing menu on the right hand side) in order to track changes.

**Comment by msrosenberg** [comment]
For reference, if you dump the manuscript to Word, in standard submission form (without tables, figures, or references), it's currently about 48 double spaced pages.

**Comment by rvosa** [comment]
I think this is now a moot issue: we are editing the manuscript collectively, it's been split up, etc. Events on the ground have overtaken this issue so to remove clutter I am going to close this.
