### ISSUE TITLE
Integrate with hackathon literature

### ISSUE THREAD

**Issue by arlin** [arlin/hip_hack_howto#28]
One of our target audiences is the small group of people who care about the process and effectiveness of participant-driven meetings.  So far as I know, there is a small literature on this.  We could find it working back from Trainer, et al.  I think we need to be familiar with this, use some of the terminology, and cite other studies.  In particular, Trainer, et al, are saying some of the same things we want to say— citing other research makes us more credible and saves space. 

The task here is (1) identify the papers to read and cite (2) read them, learn the language, and identify shared concerns, (3) integrate that knowledge into the Intro, Results and Discussion of the manuscript.

**Comment by rvosa** [comment]
Should we perhaps adopt some sensible reference management scheme, e.g. make a mendeley library, or maintain a bibtex library in a repo?

**Comment by arlin** [comment]
I have an EndNote library.  The citation markers are in double square brackets at the end.  

I can convert this to Mendeley or bibtex.  We should decide this based on the word processor, presumably.

**Comment by msrosenberg** [comment]
Has anyone used Authorea? It's theoretically designed to mix the advantages of Google Docs and Github and also include real citation support, but I've never used it.

**Comment by hlapp** [comment]
> Has anyone used Authorea? It's theoretically designed to mix the advantages of Google Docs and Github and also include real citation support, but I've never used it.

I have. It's got some nice features, but at least at the time the commenting was quite awkward because it was based on whole sections or paragraphs. I think it does use Bibtex though for reference management.

There are also [Overleaf](http://overleaf.com) (f.k.a. WriteLaTeX) and [ShareLaTeX](http://sharelatex.com). The latter integrates nicer with Github than the former, and the former interfaces directly with PeerJ submission. I have co-authored papers on both and they work well. And then there's [Lens Writer](https://github.com/substance/lens-writer), which is based on [Substance.io](http://substance.io), and [developed in collaboration with eLife](https://github.com/substance/lens-writer).

**Comment by arlin** [comment]
Collected a bunch of additional sources.  
Listed all the sources I have in a spreadsheet shared with Enrico and Rutger
Moved all of Aidan's comments into the spreadsheet 
I still need to get some references from Trainer, et al.

**Comment by arlin** [comment]
Assessed 15 sources and created notes on the spreadsheet.  This took about 4 hours.

**Comment by arlin** [comment]
Rutger and I had a chat to start consolidating our knowledge.  We are more than half done with this issue.  We drafted a bullet list of points that reference the prior literature, e.g., papers that refer to the importance of networking.  Here is the plan 
1. finish assessing about 15 more papers (Arlin, Rutger)
2. add all papers to EndNote (Arlin)
3.  expand bullet points into well-crafted sentences (Arlin, Rutger)
4. add citations to the bullet points (Arlin)
5.  make a copy of the bullet points for reference (open)  
6.  distribute the bullet points as needed in the intro, results and conclusion (open)

**Comment by arlin** [comment]
got about 15 more papers into EndNote.  This takes time when they are not indexed in pubmed.   8 more to do.

**Comment by arlin** [comment]
Finished #2, getting everything into EndNote.   Finished evaluating about 6 more brief papers.  I only have 4 left.

**Comment by arlin** [comment]
writing a summary with bullet points to help condense the material

**Comment by arlin** [comment]
We finished reading the papers.  Now @rvosa and @arlin we are working on integrating these into the manuscript.

**Comment by rvosa** [comment]
I went through it and inserted citations to the relevant papers I've read. There are now no { ref } placeholders left in the manuscript.

**Comment by arlin** [comment]
Great!  I wasn't satisfied with my previous summary  of the literature, so I made a new one here:  

 https://github.com/NESCent/hip_hack_howto/blob/master/research/lit_summary2.md

Now I'm going through and adding some of that content.

**Comment by arlin** [comment]
all the citations have been added.  we need to smooth out some of the content.  I'm going to close this.
