### ISSUE TITLE
update info on R list

### ISSUE THREAD

**Issue by arlin** [arlin/hip_hack_howto#31]
the comparative methods in R hackathon led directly to the creation of a discussion-based mailing list (r-sig-phylo) which 7 years later has XXX subscribers and generates approximately XXX messages per month.  
Here is the URL for list: https://stat.ethz.ch/pipermail/r-sig-phylo/

**Comment by rvosa** [comment]
In the manuscript I have now updated this to 8 years later, and now generating approximately 30-60 messages per month (it varies quite a bit: very low numbers during June-July). The number of subscribers needs to be looked up by the admin of r-sig-phylo.

**Comment by hlapp** [comment]
> The number of subscribers needs to be looked up by the admin of r-sig-phylo.

It is 1155 as of today.

**Comment by rvosa** [comment]
Thanks. I've added this to the manuscript, with a note of the date.
