### ISSUE TITLE
Redo the Google Trends search for figure 1

### ISSUE THREAD

**Issue by msrosenberg** [arlin/hip_hack_howto#32]
This search should be redone and the figure updated, but we likely want to wait until the last minute before submission since the data is a bit tedious to extract (Google no longer provides trend data in a downloadable or parsable form) and it could be updated over-and-over again until submission.

**Comment by arlin** [comment]
Sorry, I was getting confused between this ticket and #30 regarding  the web-o-sci search.  Did you sign up for that one?

**Comment by msrosenberg** [comment]
Yes, I signed up for that one. These are two separate issues.

**Comment by rvosa** [comment]
Done.
