### ISSUE TITLE
Correct references to application materials

### ISSUE THREAD

**Issue by arlin** [arlin/hip_hack_howto#33]
We have some stuff, but it is not properly referenced in the manuscript.

**Comment by arlin** [comment]
This worked out well.  We have several PDFs of the forms.   I found a version of the form that we have shared in the past.  I added a file to github with instructions on how to access the online template and use it to make a custom application form.

**Comment by arlin** [comment]
Needs review, assigning to Rutger.

**Comment by rvosa** [comment]
Ok. I am interpreting this to mean that we want the [appendix_materials/sample_applications](https://github.com/arlin/hip_hack_howto/tree/master/appendix_materials/sample_applications) to be explicitly referred to in the manuscript. I can do that.

**Comment by arlin** [comment]
I'm just asking for a review.  I made some references to the supplementary materials.  I just want a 2nd pair of eyes to look at that and see if it is correct and complete.

**Comment by rvosa** [comment]
OK!

**Comment by arlin** [comment]
Can this be closed?   Close if the manuscript appropriately references the application materials.
