### ISSUE TITLE
add contact information to author list

### ISSUE THREAD

**Issue by arlin** [arlin/hip_hack_howto#34]
we're working on the manuscript again, and we need your contact information.  The doc is here: 

https://docs.google.com/document/d/18kNROccM7ShyhJ6ncsBWLIi73tVjkXsCcYdR_pF6S04

**Comment by rvosa** [comment]
Shann is not in academia so it's a bit tricky to put in the "normal" department/institution/city/state/country formula in there as her affiliation. I have added as suggestion her current employer, i.e. Guardant Health, as per her LinkedIn contact details: https://www.linkedin.com/in/shannoliver
