### ISSUE TITLE
Make Lessons Learned less wordy

### ISSUE THREAD

**Issue by arlin** [arlin/hip_hack_howto#37]
The sentences and paragraphs are long.  This could be slimmed down 20 % without losing the substance of any paragraph.

**Comment by arlin** [comment]
Maybe this should just wait until we clarify the scope and conclusions.  Then it will be easier to decide what to cut.

**Comment by rvosa** [comment]
I.e. this is held up by #35

**Comment by rvosa** [comment]
This is probably redundant now that we have tickets for all the lessons. I propose close.

**Comment by arlin** [comment]
yes, agreed.  But we need a ticket to go through whole thing and reduce verbiage by perhaps 2K words.  It is over 10K right now.

**Comment by rvosa** [comment]
That's probably #54, then.
