### ISSUE TITLE
Add @arlin's timeline files

### ISSUE THREAD

**Issue by rvosa** [arlin/hip_hack_howto#4]
...and reconcile them with the milestones in the PERT chart

**Comment by arlin** [comment]
Added the milestones input file and the R-markdown code.  I still need to align this with the milestones in the PERT chart.  Align them by having identical names for some of the steps?

**Comment by rvosa** [comment]
Sounds good. Have a look at the dot source to see if the interpretation of the names does indeed make sense.

**Comment by rvosa** [comment]
As of 2cb48a88999ba0db77cbc2aecf889f2edf65f769 the milestones file is there, but the names don't completely align with the PERT chart. Do we care?

**Comment by arlin** [comment]
I think we worked it out last week, as far as it needed to go.  I'm closing this.
