### ISSUE TITLE
write up notes from meeting

### ISSUE THREAD

**Issue by arlin** [arlin/hip_hack_howto#44]

**Comment by arlin** [comment]
Argh! I wrote up notes for the meeting, then realized that Enrico had done it already on the google doc.  

I put Enrico's notes (mixed with mine) in meetings_notes.md in our howto repo.

**Comment by epontell** [comment]
I think that was Karen taking notes.

Enrico

**Comment by arlin** [comment]
my mistake. Thanks to Karen, then.
