### ISSUE TITLE
analyze a sample of products

### ISSUE THREAD

**Issue by arlin** [arlin/hip_hack_howto#48]
Following the plan developed in #47

**Comment by arlin** [comment]
Making contact with  participants from the randomly chosen set of projects.  I will use them to help me identify outcomes and explore what the downstream impacts might be. .

**Comment by arlin** [comment]
Almost done!   Still trying to figure out some Ruby stuff from hackathon #1, and then I need to go back to all my contacts to get their final comments on my write-up.

**Comment by rvosa** [comment]
This sounds like what we talked about - do you need any help with this?

**Comment by arlin** [comment]
Yes, please respond to the email that I sent.  The final step in the process is to get feedback on my summaries of each project.  Then I'll be done with this.

**Comment by arlin** [comment]
2nd (and final) request for feedback has been sent.

**Comment by arlin** [comment]
Feedback deadline has passed.  Made final revisions.  Removed names and initials and referred to participant numbers instead.  I'm closing this.
