### ISSUE TITLE
render pert chart as an image

### ISSUE THREAD

**Issue by msrosenberg** [arlin/hip_hack_howto#5]
There had been a pdf of an older version, but it's been deleted/superseded by the updated version.

**Comment by rvosa** [comment]
Yes: I think it is better to have one "authoritative" version for now, so
they don't go out of sync. To this end the available version is in dot
language, not OmniGraffle, so that everyone - even windows users - can view
it on the freely available GraphViz.

**Comment by rvosa** [comment]
Closing this issue, tagged as 'wontfix', for reasons given above.
