### ISSUE TITLE
start formatting draft for F1000

### ISSUE THREAD

**Issue by arlin** [arlin/hip_hack_howto#54]
see http://f1000research.com/for-authors/article-guidelines.  No need to be complete at this point because we may have to reformat when we move this to Word.

**Comment by rvosa** [comment]
I would be happy to have this assigned. I assume this means: look up the guidelines and go through the MS to see how far away we are from them. Add comments to point out areas that need concerted effort, make smaller fixes opportunistically at will.

**Comment by msrosenberg** [comment]
I could also do this

**Comment by arlin** [comment]
Rutger, if you are eager to do some work, let's talk about the deep dive.  It would be fun to talk anyway.  I'll assign this to Mike instead, OK?

**Comment by rvosa** [comment]
Sure, sounds good.

**Comment by msrosenberg** [comment]
Just to confirm, the current version of the MS is the GoogleDoc linked from the ReadMe for this github repository? I'm pretty sure that's the correct one, but I don't want to start formatting the wrong version of the MS.

**Comment by arlin** [comment]
yes, that's the one.
