### ISSUE TITLE
Renaming the "NESCent Model"

### ISSUE THREAD

**Issue by msrosenberg** [arlin/hip_hack_howto#6]
We had discussed that this may not be the best name. Placing the reminder here that we need to think about this.

**Comment by hlapp** [comment]
My thoughts on this is that the label should reflect the distinguishing priorities in some way. The most salient of these, IMHO, is the community nurturing one.

**Comment by arlin** [comment]
My thoughts: 
1.  Short labels are better.  
2.  If no one else is doing hackathons like ours, then IMHO we are OK to call it "the NESCent model".  If BOSC used to do them, but isn't anymore, and they haven't left a documentation trail, then IMHO they have defaulted on the naming rights. 
3.  The "community" label is thematically appropriate, but it also suggests a reference to the "community hackathon" concept, which is a double-edged sword if potential readers see this as a special sub-species of hackathon.  On the one hand, it could help to grab attention (and google searches) from people who want to stage an event that they think of as a "community hackathon".  On the other hand, it could turn away people who think they are planning something else (an "in-house" hackathon), and assume that our docs are inappropriate (whereas my belief is that our model is appropriate for various kinds of hackathons). 

But point 3 doesn't matter if "community hackathon" isn't in people's heads already as a restrictive sub-type of hackathons.  I don't know.

**Comment by aidanbudd** [comment]
How about dropping the "Model" part of the name - just calling them "NESCent hackathons"?

**Comment by rvosa** [comment]
If it has NESCent in the name it should probably have Model in the name as well. Just to clarify that this is a model that others could (should) adopt rather than this being exclusive to a specific organization (that is ceasing operations).

**Comment by msrosenberg** [comment]
We seem to be sticking with this name, so I'm closing this issue.
