### ISSUE TITLE
Why did Phylostars fail?

### ISSUE THREAD

**Issue by msrosenberg** [arlin/hip_hack_howto#7]
We had planned and gotten funding to do a Phylostars hackathon, but the project fell apart. What lessons can be learned from this experience?

**Comment by msrosenberg** [comment]
One of the major reasons was that the project relied heavily on the participation of a single person who essentially backed out of the project. Clearly designing a project reliant on support of a particular individual is a poor idea.

**Comment by arlin** [comment]
It wasn't quite like that.  This proposal was a "reach" from the start, in the sense that none of the proposers were active members in communities such as StackOverflow or BioStars.  Once we got funded, we made a connection with a key person from one of those resources, which was smart and appropriate thing to do.  However, this person almost immediately backed away when faced with the relatively modest requirement of attending a teleconference every 2 weeks for an hour.  Then another member of the original team backed away.  All along, we were struggle with the idea that this project was not located in the center of our own expertise.
