### ISSUE TITLE
update description of lit search ca. line 105

### ISSUE THREAD

**Issue by arlin** [arlin/hip_hack_howto#80]
this currently refers to the literature through 2014, which is too long ago.  I would recommend to distinguish the scholarly literature from news reports.  We have a list of about 40 sources in the spreadsheet below, and this could be used to make a statement that is up-to-date as of spring 2016. 

https://docs.google.com/spreadsheets/d/1ZhiDyySP0PIgWJvJPXWtVw22vUaJ89hupwHB84Bq6b8/edit#gid=0

I'm assigning this to RV or me because we are the ones who did this.  I don't know why we didn't update this particular statement previously.

**Comment by rvosa** [comment]
I would argue that we have now incorporated our literature study results in the manuscript and, hence, this issue can be closed.
