### ISSUE TITLE
read through manuscript

### ISSUE THREAD

**Issue by kcranston** [arlin/hip_hack_howto#9]
Before March 27, @arlin and @aidanbudd and me need to read through the manuscript. Key questions:
1. What is missing?
2. What is wrong?
3. What can we answer with data that we have?

**Comment by aidanbudd** [comment]
Done my read-through.

**Comment by arlin** [comment]
I have done my read-through.  I think we are going to have to discuss item 3 (What can we answer with data that we have?) when we meet again.

**Comment by msrosenberg** [comment]
has everyone had a chance to give their initial comments? Arlin did a lot of revising, but I don't want to step in and figure out the next big step until everyone had at least given the text a first pass.

**Comment by kcranston** [comment]
I'll give it a read-through this afternoon.

On Wed, Mar 25, 2015 at 11:47 AM, Michael Rosenberg <
notifications@github.com> wrote:

> has everyone had a chance to give their initial comments? Arlin did a lot
> of revising, but I don't want to step in and figure out the next big step
> until everyone had at least given the text a first pass.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arlin/hip_hack_howto/issues/9#issuecomment-86089881.

## 

```
karen.cranston@gmail.com
@kcranstn
```

**Comment by shannoliver** [comment]
Yep

**Comment by epontell** [comment]
Will try to read tomorrow

**Comment by rvosa** [comment]
done, made edits, additions and comments:
https://github.com/arlin/hip_hack_howto/commit/0861899a075a27239d8a2d9185c4fe48a8f17ad3

**Comment by rvosa** [comment]
Has everyone had a chance to read through, by the way? I don't see a confirmation from @hlapp yet. How should we proceed? In my assessment the contours are starting to take shape but there's obviously still quite a bit to do. I think it would make sense to actually define what needs doing and break that up into milestone issues. These might include:
- deal with the inline comments - either resolve in place or create an issue
- make a bibliography out of the stuff at the bottom (e.g. bibtex or mendeley)
- merge/move some parts (e.g. "Approach I: The "NESCent Hackathon" Process Model" and "What makes the NESCent model different?")

Anyway, lots of other things we can think of. Point being, how shall we proceed?

**Comment by epontell** [comment]
Shall we schedule a call to talk about the manuscript.

## Enrico

College of Arts & Sciences
New Mexico State University
Las Cruces, NM 88003

**Comment by hlapp** [comment]
> Has everyone had a chance to read through, by the way? I don't see a confirmation from @hlapp yet.

I've been one of the main writers, so yes, I've read (and in part written) the text.

**Comment by rvosa** [comment]
Great. Maybe I just asked for completeness. So how should we proceed?

**Comment by msrosenberg** [comment]
Since I said I'd supervise the MS I was waiting until this morning (it's only 9am where I am) to give everyone a last chance to read through it. Either later today or tomorrow I'm going to go through the whole thing and evaluate the status to decide on what the next step should be.

**Comment by arlin** [comment]
Rutger, the part that you missed at the end of the hackathon was where we committed to a plan to finish. I summarized it in a March 16 email.  Here is the bit about the manuscript (there is another part about the data): 
1. Manuscript.  We agreed that the manuscript comes first: we’ll choose a venue once we see the manuscript take shape.  We decided on a group-writing model.  We did not come to consensus on the issue of group authorship versus some other way of assigning authorship.  Instead, we had a majority of 5 in favor of group authorship, with considerable unease about the decision, and so we decided to revisit this issue later. 
2. Mike will be the lead (manager) of writing
3. everyone will be part of writing and will commit to it for 2 weeks or until we finish the “to do” list
4. Karen, Arlin and Aidan need to read through the raw text by March 29 and ask 3 questions (see notes)
5. we’ll use the wikipedia model on the markdown file until Mike decides its time to move
6. then we’ll use the lead-author model of writing on a gdoc (or something to be determined)
7. please research venue options and add the info to the mopad notes

**Comment by rvosa** [comment]
Ah, thanks. Sorry to be out of the loop / out of sync.

**Comment by msrosenberg** [comment]
I'm closing this thread. I'll post new issues once I've evaluated for the next step.
